server:
  port: 2020
spring:
  application:
    name: school_airdrop_im
  datasource:
    url: jdbc:mysql://192.168.73.128:3306/school_airdrop_im?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: kennen
  jpa:
    show-sql: true
  redis:
    host:  192.168.73.128 # Redis服务器地址
    port:  6379 # Redis服务器连接端口
    password:  schoolairdrop_kennen # Redis服务器连接密码
